# Generated by Django 3.2.13 on 2022-04-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tglMasuk', models.DateField()),
                ('nmrMat', models.CharField(max_length=200)),
                ('descMat', models.CharField(max_length=200)),
                ('jmlMat', models.IntegerField()),
                ('satuan', models.CharField(max_length=200)),
                ('hargaSat', models.IntegerField()),
                ('imgMat', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
