# Generated by Django 3.2.13 on 2022-05-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_inoutmaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InOutMaterial',
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='tglMasuk',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Masuk'),
        ),
    ]
