# Generated by Django 3.2.13 on 2022-05-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220505_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOutMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tglIn', models.DateField(verbose_name='Tanggal Masuk')),
                ('tglOut', models.DateField(verbose_name='Tanggal Keluar')),
                ('nmrMat', models.CharField(max_length=200, verbose_name='Nomor Material')),
                ('descMat', models.CharField(max_length=200, verbose_name='Deskripsi Material')),
                ('jmlMat', models.IntegerField(verbose_name='Jumlah Material')),
                ('matIn', models.IntegerField(verbose_name='Material Masuk')),
                ('matOut', models.IntegerField(verbose_name='Material Keluar')),
                ('satuan', models.CharField(max_length=200, verbose_name='Satuan')),
                ('hargaSat', models.IntegerField(verbose_name='Harga Satuan')),
                ('totalMat', models.IntegerField(verbose_name='Total Material')),
            ],
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='matIn',
            field=models.IntegerField(default=0, verbose_name='Material Masuk'),
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
