# Generated by Django 3.2.13 on 2022-05-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_inputmodel_matout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutmaterial',
            name='matIn',
            field=models.IntegerField(default=0, verbose_name='Material Masuk'),
        ),
        migrations.AlterField(
            model_name='inoutmaterial',
            name='matOut',
            field=models.IntegerField(default=0, verbose_name='Material Keluar'),
        ),
    ]
