# Generated by Django 3.2.13 on 2022-05-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220506_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='matIn',
            field=models.IntegerField(blank=True, default=0, verbose_name='Material Masuk'),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='matOut',
            field=models.IntegerField(blank=True, default=0, verbose_name='Material Keluar'),
        ),
    ]
