# Generated by Django 3.2.13 on 2022-05-07 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220506_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='tglMasuk',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Tanggal Masuk'),
            preserve_default=False,
        ),
    ]
