# Generated by Django 3.2.13 on 2022-05-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_inputmodel_tglmasuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='tglMasuk',
            field=models.DateField(verbose_name='Tanggal Masuk'),
        ),
    ]
