# Generated by Django 3.2.13 on 2022-05-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_inputmodel_tglmasuk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inoutmaterial',
            name='totalMat',
        ),
    ]
