# Generated by Django 3.2.13 on 2022-05-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_inoutmaterial_totalmat'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutmaterial',
            name='random',
            field=models.IntegerField(default=1, verbose_name='Random'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='random',
            field=models.IntegerField(default=3, verbose_name='Random'),
            preserve_default=False,
        ),
    ]
