# Generated by Django 3.2.13 on 2022-05-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20220509_0642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inputmodel',
            unique_together={('nmrMat',)},
        ),
    ]
